# ----------------------------------------
# General
# path to sheet describing each cell
library_info: "samplesheets/library_info.tsv"
# output directory for processed data

base: "/oak/stanford/groups/quake/shared/swiftShare/TBD_gex"
outs_basedir: "/oak/stanford/groups/quake/shared/swiftShare/TBD_gex"
# specificed in multi_configs
fastq_dir: "/oak/stanford/groups/quake/shared/swiftShare/sym_scTB"
# human or mouse
species: human
# partition (for cluster computing)
partition: "quake,owners"
workflow_dir: "/home/groups/quake/mswift/tabula-bursa/snakemake_workflow"
samplesheets: ["samplesheets/samplesheet_gex.tsv"]
# Software
#---------------------------
cell_ranger: "/home/groups/quake/mswift/resources/cellranger-6.0.1"
resources: "/home/groups/quake/mswift/5prime_10X_workflow/resources"

# references
#------------
vdj_ref_prefix: "vdj_human"
cell_ranger_ref: "/oak/stanford/groups/quake/mswift/resources/cellranger/refdata-cellranger-vdj-GRCh38-alts-ensembl-3.1.0/"

10X_transcriptome: "https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-GRCh38-2020-A.tar.gz"
transcriptome: "/home/groups/quake/mswift/tabula-bursa/snakemake_workflow/db/refdata-gex-GRCh38-2020-A"
# the assembly pipeline uses the immcantation framework for IgBLAST
# options: 'docker' or 'singularity'
container_type: singularity
# STAR alignment: fasta and gtf files
# (these should not need to be changed)
ighc_db:
  human: db/IGHC/human_IGHC_IMGT_membrane_only_reformatted.fasta
  imgt_exons: db/IGHC/IGHC_exons.bed
  imgt_introns: db/IGHC/IGHC_introns_inner.bed
  mouse: db/IGHC/mouse_IGHC_IMGT_reformatted.fast
# Igblast
IGDBDIR: /oak/stanford/groups/quake/shared/swiftShare/igblast
path_to_grmlin: /home/users/cvijovic/ig-germline-discovery/grmlin/
scripts: ./scripts