# ----------------------------------------
# General
# path to sheet describing each cell
library_info: "samplesheets/library_info.tsv"
# output directory for processed data
base: "/oak/stanford/groups/quake/shared/swiftShare/tabula_bursa_pipeline"
outs_basedir: "/oak/stanford/groups/quake/shared/swiftShare/tabula_bursa_pipeline"
# specificed in multi_configs

fastq_dirs: ["/oak/stanford/groups/quake/shared/swiftShare/ilm4_gex/Ivana_Cvijovic/", "/oak/stanford/groups/quake/shared/swiftShare/ilm6_gex/Ivana_Cvijovic/"]
fastq_dirs: ["/oak/stanford/groups/quake/shared/swiftShare/all_gex_fastqs/"]
vdj_fastq_dir: "/oak/stanford/groups/quake/shared/swiftShare/ilm7_vdj/"

# human or mouse
species: human
# partition (for cluster computing)
partition: "quake,owners"
workflow_dir: "/home/groups/quake/mswift/tabula-bursa/snakemake_workflow" 
samplesheets: ["samplesheets/samplesheet.tsv"]
# Software
#---------------------------

cell_ranger: "/home/groups/quake/mswift/resources/cellranger-7.0.1"
resources: "/home/groups/quake/mswift/5prime_10X_workflow/resources"

# references
#------------
vdj_ref_prefix: "vdj_human"
vdj_reference: "/home/groups/quake/mswift/5prime_10X_workflow/db/vdj_reference"
inner_primers: "/home/groups/quake/mswift/tabula-bursa/snakemake_workflow/db/inner_primers.txt"
10X_transcriptome: "https://cf.10xgenomics.com/supp/cell-exp/refdata-gex-GRCh38-2020-A.tar.gz"
transcriptome: "/home/groups/quake/mswift/tabula-bursa/snakemake_workflow/db/refdata-gex-GRCh38-2020-A"
# the assembly pipeline uses the immcantation framework for IgBLAST
# options: 'docker' or 'singularity'
container_type: singularity
# STAR alignment: fasta and gtf files
# (these should not need to be changed)
ighc_db:
  human: db/IGHC/human_IGHC_IMGT_membrane_only_reformatted.fasta
  imgt_exons: db/IGHC/IGHC_exons.bed
  imgt_introns: db/IGHC/IGHC_introns_inner.bed
  mouse: db/IGHC/mouse_IGHC_IMGT_reformatted.fast
# Igblast
IGDBDIR: /oak/stanford/groups/quake/shared/swiftShare/igblast
scripts: 
path_to_grmlin:
# params:
decontX_mode: filtered