__default__:
    time: '8:00:00'
    name: "{rule}"
    partition: normal,owners,quake
    mem_mb: '32000'
    ntasks: '1'
    cpus-per-task: '2'
    output: 'snakemake_logs/slurm_logs/{rule}_%j.out'
    error: 'snakemake_logs/slurm_logs/{rule}_%j.err'

cellranger_count:
    time: '48:00:00'
    name: '{rule}'
    partition: quake,owners
    mem_mb: '128000'
    ntasks: '1'
    cpus-per-task: '20'
    output: 'snakemake_logs/slurm_logs/{rule}_%j.out'
    error: 'snakemake_logs/slurm_logs/{rule}_%j.err'

aggregate_gex:
    time: '1:00:00'
    name: '{rule}'
    partition: quake
    mem_mb: '120000'
    ntasks: '1'
    cpus-per-task: '20'
    output: 'snakemake_logs/slurm_logs/{rule}_%j.out'
    error: 'snakemake_logs/slurm_logs/{rule}_%j.err'

preprocess_scanpy:
    time: '4:00:00'
    name: '{rule}'
    partition: quake
    mem_mb: '128000'
    ntasks: '1'
    cpus-per-task: '20'
    output: 'snakemake_logs/slurm_logs/{rule}_%j.out'
    error: 'snakemake_logs/slurm_logs/{rule}_%j.err'

run_decontx:
    time: '2:00:00'
    name: '{rule}'
    partition: quake,owners
    mem_mb: '128000'
    ntasks: '1'
    cpus-per-task: '20'
    output: 'snakemake_logs/slurm_logs/{rule}_%j.out'
    error: 'snakemake_logs/slurm_logs/{rule}_%j.err'

preprocess_scanvi:
    time: '1:00:00'
    name: '{rule}'
    partition: quake,owners
    mem_mb: '210000'
    ntasks: '1'
    cpus-per-task: '20'
    output: 'snakemake_logs/slurm_logs/{rule}_%j.out'
    error: 'snakemake_logs/slurm_logs/{rule}_%j.err'
